const data = [
  {
    id: 40104,
    category: 0,
    first_release_date: 1988,
    genres: [5],
    name: "Dogou Souken",
    platforms: [52],
    similar_games: [12364, 27270],
    summary: "An overhead-view shoot'em up game.",
    url: "https://www.igdb.com/games/dogou-souken",
  },
  {
    id: 30981,
    category: 8,
    first_release_date: 1966,
    genres: [2],
    name: "Pokemon",
    platforms: [70],
    similar_games: [12364, 27270],
    summary: "Gotta catch them all",
    url: "https://www.igdb.com/games/pokemon",
  },
  {
    id: 30981,
    category: 8,
    first_release_date: 1966,
    genres: [2],
    name: "Digimon",
    platforms: [70],
    similar_games: [12364, 27270],
    summary: "darker than pokemon",
    url: "https://www.igdb.com/games/digimon",
  },
  {
    id: 30981,
    category: 8,
    first_release_date: 1966,
    genres: [2],
    name: "Persona 5",
    platforms: [70],
    similar_games: [12364, 27270],
    summary: "digimonmon",
    url: "https://www.igdb.com/games/persona5",
  },
  {
    id: 30981,
    category: 8,
    first_release_date: 1966,
    genres: [2],
    name: "metal gear",
    platforms: [70],
    similar_games: [12364, 27270],
    summary: "Gotta catch them all",
    url: "https://www.igdb.com/games/mgs",
  },
  {
    id: 30981,
    category: 8,
    first_release_date: 1966,
    genres: [2],
    name: "final fantasy",
    platforms: [70],
    similar_games: [12364, 27270],
    summary: "crystals yuh",
    url: "https://www.igdb.com/games/finalfantasy",
  },
];

export default data;
